import os 
import numpy as np
from PIL import Image

import torch
from diffusers import StableDiffusionPipeline
import streamlit as st 

#function to generate AI based images using Huggingface Diffusers
def generate_images_stable_diffusion(prompt, model_path):
    pipe = StableDiffusionPipeline.from_pretrained(model_path,
        torch_dtype=torch.float16)
    pipe = pipe.to("cuda")
    num_inference_steps = 50
    guidance_scale = 7.5
    image = pipe(prompt, num_inference_steps=num_inference_steps, guidance_scale=guidance_scale).images[0]
    return image

st.title("Text2Image Specialized in Cartoons")
with st.expander("About the App"):
    st.write("Image generation app that uses the stable-diffusion AI\
         trained on cartoon dataset to generates images from text prompt.")

st.subheader("Image generation using Huggingface Diffusers")

model_path = st.text_input("Enter the path of cartoon-blip-captions-model")
input_prompt = st.text_input("Enter your text prompt")

if input_prompt is not None:
    if st.button("Generate Image"):
        image_output = generate_images_stable_diffusion(input_prompt, model_path)
        st.info("Generating image.....")
        st.success("Image Generated Successfully")
        st.image(image_output, caption="Generated by Huggingface Diffusers")
